FROM eclipse-temurin:17.0.3_7-jre-alpine

EXPOSE 35353/tcp
EXPOSE 25565/tcp
WORKDIR /app

ADD https://multipaper.io/api/v2/projects/multipaper/versions/{version}/builds/{build}/downloads/{jar_file} /

ENTRYPOINT if [[ -n "$EULA" ]]; then \
                echo "eula=$EULA" > eula.txt; \
           fi && \
           exec java -jar /{jar_file}

CMD ["-nogui", "--host=0.0.0.0"]

