FROM eclipse-temurin:17.0.3_7-jre-alpine

EXPOSE 35353/tcp
EXPOSE 25565/tcp
WORKDIR /app

ENTRYPOINT ["/run.sh", "/{jar_file}"]
CMD []

ADD run.sh https://multipaper.io/api/v2/projects/multipaper/versions/{version}/builds/{build}/downloads/{jar_file} /

