name: Auto Check Latest Version

on:
  schedule:
    - cron: '*/30 * * * *'
  push:
    branches:
      - 'main'

jobs:
  cron:
    name: Push Docker image to multiple registries
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write # To push a branch 
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Show repo tags
        run: git ls-remote --tags

      - name: Get next version
        run: ./next-versions.sh

      - name: Multipaper version
        run: |
          echo "VERSION: ${{ env.VERSION }}"
          echo "BUILD: ${{ env.BUILD }}"
          echo "MASTER_VERSION: ${{ env.MASTER_VERSION }}"
          echo "SERVER_VERSION: ${{ env.SERVER_VERSION }}"

      - name: Configure Git
        run: |
          git config user.name "akiicat"
          git config user.email "aaaa1379@gmail.com"

      - name: Commit
        run: |
          git add -A
          git commit -m "[AUTO] multipaper server v${{ env.SERVER_VERSION }}" -m "Co-authored-by: github-actions[bot] <github-actions[bot]@users.noreply.github.com>"

      - name: Add Tag
        run: |
          git tag "v${{ env.SERVER_VERSION }}"

      - name: Push
        run:
          git push --atomic origin main "v${{ env.SERVER_VERSION }}"
