name: Auto Check Latest Version

on:
  schedule:
    - cron: '*/30 * * * *'
  push:
    branches:
      - 'main'

jobs:
  cron:
    name: Push Docker image to multiple registries
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Show repo tags
        run: git ls-remote --tags

      - name: Get next version
        run: ./next-versions.sh

      - name: Multipaper version
        run: |
          echo "VERSION: ${{ env.VERSION }}"
          echo "BUILD: ${{ env.BUILD }}"
          echo "MASTER_VERSION: ${{ env.MASTER_VERSION }}"
          echo "SERVER_VERSION: ${{ env.SERVER_VERSION }}"

      - name: Auto commit to Github
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          # repo and workload scopes
          tagging_message: "v${{ env.SERVER_VERSION }}"
          commit_message: "[AUTO] multipaper server v${{ env.SERVER_VERSION }}"

